# Generated by Django 5.0.4 on 2024-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('scoreDate', models.DateTimeField(verbose_name='score date')),
            ],
        ),
    ]
